import { ReactNode } from 'react'
import { useLocation } from 'react-router-dom'

interface LayoutProps {
  children: ReactNode
}

const Layout = ({ children }: LayoutProps) => {
  const location = useLocation();
  // Show Home button only on Data Entry and Report pages
  const showHome = location.pathname === '/data-entry' || location.pathname === '/report';
  return (
    <div className="min-h-screen bg-gradient-to-br from-gray-50 via-blue-50 to-blush-light font-sans">
      {/* Header (hidden in print) */}
      <header className="sticky top-0 z-30 bg-gradient-to-r from-primary via-blue-100 to-blush-light shadow-soft py-2 print:hidden">
        <div className="max-w-7xl mx-auto px-4 sm:px-6 lg:px-8">
          <div className="flex justify-between items-center py-4">
            <div className="flex items-center">
              <h1 className="text-3xl font-extrabold text-primary-dark uppercase tracking-widest drop-shadow-sm">FALCON</h1>
              <span className="ml-3 text-lg text-gray-700 font-light tracking-tight">Dialysis Surveillance Report Generator</span>
            </div>
            <nav className="flex space-x-2">
              {showHome && (
                <a href="/" className="px-4 py-2 rounded-full bg-white/80 text-primary font-semibold shadow transition hover:bg-primary hover:text-white">Home</a>
              )}
            </nav>
          </div>
        </div>
      </header>

      {/* Main Content */}
      <main className="max-w-7xl mx-auto px-4 sm:px-6 lg:px-8 py-10">
        <div className="rounded-2xl bg-white/90 shadow-soft p-6 sm:p-10 transition-all duration-300">
          {children}
        </div>
      </main>

      {/* Footer */}
      <footer className="bg-gradient-to-r from-primary-light via-gray-50 to-blush-light border-t mt-10">
        <div className="max-w-7xl mx-auto px-4 sm:px-6 lg:px-8 py-6">
          <p className="text-center text-gray-500 text-base tracking-widest font-sans" style={{ fontFamily: 'Figtree, Inter, Arial, sans-serif', letterSpacing: '0.15em', fontWeight: 600 }}>
            Generated by <span className="text-primary font-extrabold" style={{ fontFamily: 'Figtree, Inter, Arial, sans-serif', fontWeight: 900, fontSize: '1.15em', letterSpacing: '0.18em' }}>Falcon</span> <span className="mx-1">©</span> Designed by <span className="text-accent font-extrabold" style={{ fontFamily: 'Figtree, Inter, Arial, sans-serif', fontWeight: 900, fontSize: '1.15em', letterSpacing: '0.18em' }}>Ali Ashery</span>
          </p>
        </div>
      </footer>
    </div>
  )
}

export default Layout 